config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
   end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_create :update_counter
  after_destroy :update_counter

  private

  def update_counter
    post.comments_count = post.comments.count
    post.save
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_create :update_counter
  after_destroy :update_counter

  private

  def update_counter
    post.likes_count = post.likes.count
    post.save
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_create :update_counter
  after_destroy :update_counter

  def recent_comments
    comments.last(5).reverse
  end

  private

  def update_counter
    author.posts_count = author.posts.count
    author.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  validates :name, presence: true
  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_post
    posts.last(3).reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = current_user
    @post = Post.find(params[:post_id])
    render 'new'
  end

  def create
    Comment.create(text: params[:comment][:text], author_id: params[:user_id], post_id: params[:post_id])
    redirect_to "/users/#{params[:user_id]}/posts/#{params[:post_id]}"
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user = current_user
    Like.create(author: user, post: Post.find(params[:post_id]))
    redirect_to "/users/#{params[:user_id]}/posts/#{params[:post_id]}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(posts: [:comments]).find(params[:user_id])
    if @user.posts.empty?
      redirect_to "/users/#{params[:user_id]}/posts/new"
    else
      render 'index'
    end
  end

  def show
    @post = Post.find(params[:id])
    render 'show'
  end

  def new
    @user = User.find(params[:user_id])
    render 'new'
  end

  def create
    user = current_user
    puts user
    post = Post.new(title: params[:title], text: params[:text], author_id: user.id, comments_count: 0, likes_count: 0)
    if post.save
      redirect_to "/users/#{user.id}/posts", notice: 'new post created successfully'
    else
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render 'index'
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_post
    render 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/posts.css" %>
  </head>

  <body>
    <div class="container">


          <%= form_with model: @comment, url: user_post_comments_path, method: :post, scope: :comment, class: "comments_form" do |f| %>
            <%= f.text_field :text, place_holder: "Enter the comment text" %>
            <%= f.submit "Create" %>
          <% end %>

    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav_menu_header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/posts.css" %>
  </head>

  <body>
    <div class="container">
        <div class="user-info">
            <%=image_tag(@user.photo, class: 'profile-photo') unless @user.photo.nil?%>

            <div class="user-details">
                <h3><%=@user.name%></h3>
                <p>Number of post: <%=@user.posts.count%></p>
            </div>
        </div>

        <ul class="posts">
          <%@user.posts.each do |post|%>
          <li class="post">
            <div>
              <%= link_to "/users/#{@user.id}/posts/#{post.id}" do %>
              <h3><%=post.title%></h3>
            <%end%>
              <p>
                <%=post.text%>
              </p>
              <p class='likes-coomments'>Comments: <%=post.comments.count%>, Likes: <%=post.likes.count%></p>
            </div>
            <div class="comments">
                <ul class="commens-list">
                <%post.recent_comments.each do |comment|%>
                    <li>
                        <p><%="#{comment.author.name}: #{comment.text}"%></p>
                    </li>
                  <%end%>
                </ul>
            </div>
          </li>
          <%end%>
        </ul>
        <%=link_to "/users/#{@user.id}/posts/new" do%>
          <%=button_to "New post", class: 'all-posts'%>
        <%end%>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/posts.css" %>
  </head>

  <body>
    <div class="container">
          <%= form_with model: @post, url: user_posts_path(@user), method: :post, class: "comments_form" do |f| %>
            <div>
                <%= f.label :title %>
                <%= f.text_field :title %>
                <%= f.label :text %>
                <%= f.text_field :text %>
            </div>
            <%= f.submit "Create" %>
          <% end %>

    </div>
  </body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/post_info.css" %>
  </head>

  <body>
    <div class="container">
        <div class="pos">
          <div class="post-info">
            <div>
                <h3><%="#{@post.title} by #{@post.author.name}"%></h3>
                <p class='likes-comments'>Comments: <%=@post.comments.count%>, Likes: <%=@post.likes.count%></p>
            </div>
            <p>
            <%=@post.text%>
            <%= form_with url: user_post_likes_path(@post.author, @post), class: 'like_button' do |form| %>
              <%= form.submit 'Like' %>
            <% end %>
            </p>
          </div>
          <div class="comments">
              <ul class="commens-list">
                <%@post.comments.each do |comment|%>
                    <li>
                        <p><%="#{comment.author.name}: #{comment.text}"%></p>
                    </li>
                <%end%>
              </ul>
          </div>
          <%=button_to "Leave a comment", "/users/#{@post.author.id}/posts/#{@post.id}/comments/new", class: 'all-posts', method: 'get'%>
        </div>
    </div>
  </body>
</html>

app/views/shared/_nav_menu_header.html.erb
<header class="w-full p-4">
  <div class="flex flex-wrap items-center justify-end gap-4 w-10/12 mx-auto">
    <% if user_signed_in? %>
      <%= button_to 'Sign out', destroy_user_session_path, form_class: 'px-4 py-2 border-2 border-black cursor:pointer', method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class: 'px-4 py-2 border-2 border-black cursor:pointer'  %>
      <%= link_to "Sign up", new_user_registration_path, class: 'px-4 py-2 border-2 border-black cursor:pointer'  %>
    <% end %>
  </div>
</header>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/index.css" %>
  </head>

  <body>
    <div class="container">
    <h1>
    </h1>
        <ul class="user-list">
           <%@users.each do |user|%>
             <li>
                 <%=image_tag(user.photo, class: 'profile-photo') unless user.photo.nil?%>

                 <div class="user-details">
            <%= link_to "/users/#{user.id}", id: "link-to-#{user.name}" do %>
                     <h3><%=user.name%></h3>
            <%end%>
                     <p>Number of post: <%=user.posts.count%></p>
                 </div>
             </li>
            <%end%>
        </ul>
    </div>
  </body>
</html>

app/views/users/post_info.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/post_info.css" %>
  </head>

  <body>
    <div class="container">
        <div class="pos">
          <div class="post-info">
            <div>
                <h3>Post #1 by username</h3>
                <p class='likes-comments'>Comments: x, Likes:x</p>
            </div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate. Sed vel dolor porttitor felis aliquam tincidunt. Sed nibh orci, dictum sit amet sodales ac, pharetra in augue. Donec rhoncus vehicula magna. Sed laoreet fermentum tincidunt. Curabitur semper elit ac dui commodo, sed lobortis urna varius. Nulla risus neque, euismod ut ante ut, scelerisque luctus leo. Fusce congue dui at eros porta lacinia.

                Nunc vitae nisi vel dolor rutrum convallis. Maecenas volutpat sapien et arcu scelerisque lacinia. Praesent aliquam leo a ipsum aliquet, at aliquet ante vehicula. In in accumsan tellus, vel bibendum metus. Etiam volutpat, ligula vitae scelerisque sollicitudin, velit orci consectetur est, et porta dui justo et elit. Donec non pharetra ligula. Maecenas euismod leo a mauris viverra aliquet. Donec a lectus ante. Fusce non lacus venenatis lacus ornare fermentum vel eu purus. Praesent fermentum lacus ac quam rhoncus egestas. Suspendisse bibendum arcu vitae ex vulputate, nec commodo libero tristique. Etiam sed blandit sem. Quisque quis venenatis sem. Nam a aliquet velit.
            </p>
          </div>
          <div class="comments">
              <ul class="commens-list">
                  <li>
                      <p>Username: comment1</p>
                  </li>
                  <li>
                      <p>Username: comment2</p>
                  </li>
                  <li>
                      <p>Username: comment3</p>
                  </li>
                  <li>
                      <p>Username: comment4</p>
                  </li>
                  <li>
                      <p>Username: comment5</p>
                  </li>
                  <li>
                      <p>Username: comment6</p>
                  </li>
                  <li>
                      <p>Username: comment7</p>
                  </li>
                  <li>
                      <p>Username: comment8</p>
                  </li>
                  <li>
                      <p>Username: comment9</p>
                  </li>
                  <li>
                      <p>Username: comment10</p>
                  </li>
              </ul>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/users/posts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/posts.css" %>
  </head>

  <body>
    <div class="container">
        <div class="user-info">
            <div class="profile-photo">
            <p>photo</p>
            </div>

            <div class="user-details">
                <h3>User Name</h3>
                <p>Number of post: x</p>
            </div>
        </div>

        <ul class="posts">

          <li class="post">
            <div>
              <h3>Post #1</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate.
              </p>
              <p class='likes-coomments'>Comments: x, Likes:x</p>
            </div>
            <div class="comments">
                <ul class="commens-list">
                    <li>
                        <p>Username: comment1</p>
                    </li>
                    <li>
                        <p>Username: comment2</p>
                    </li>
                    <li>
                        <p>Username: comment3</p>
                    </li>
                    <li>
                        <p>Username: comment4</p>
                    </li>
                    <li>
                        <p>Username: comment5</p>
                    </li>
                </ul>
            </div>
          </li>

          <li class="post">
            <div>
              <h3>Post #2</h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate.
              </p>
              <p class='likes-coomments'>Comments: x, Likes:x</p>
            </div>
            <div class="comments">
                <ul class="commens-list">
                    <li>
                        <p>Username: comment1</p>
                    </li>
                    <li>
                        <p>Username: comment2</p>
                    </li>
                    <li>
                        <p>Username: comment3</p>
                    </li>
                    <li>
                        <p>Username: comment4</p>
                    </li>
                    <li>
                        <p>Username: comment5</p>
                    </li>
                </ul>
            </div>
          </li>
        </ul>
        <button class="all-posts">Pagination</button>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/user_info.css" %>
  </head>

  <body>
    <div class="container">
        <div class="user-info">
            <%=image_tag(@user.photo, class: 'profile-photo') unless @user.photo.nil?%>

            <div class="user-details">
                <h3><%=@user.name%></h3>
                <p>Number of post: <%=@user.posts_count%></p>
            </div>
        </div>

        <div class="bio">
        <h3>Bio</h3>
            <%=@user.bio%>
        </div>

        <ul class="post-list">
          <%@recent_posts.each do |post|%>
          <li>
          <%= link_to "/users/#{@user.id}/posts/#{post.id}", id:"post_#{post.id}_link" do %>
            <h3><%=post.title%></h3>
          <%end%>
            <p>
              <%=post.text%>
            </p>
            <p class='likes-coomments'>Comments: <%=post.comments_count%>, Likes: <%=post.likes.count%></p>
          </li>
          <%end%>
          <%="#{@user.name} has no any post" unless !@user.posts.empty?%>
        </ul>
        <%=button_to "See all posts", "/users/#{@user.id}/posts", class: 'all-posts', id: "users-#{@user.id}", method: :get%>
    </div>
  </body>
</html>

app/views/users/user_info.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag "/users/user_info.css" %>
  </head>

  <body>
    <div class="container">
        <div class="user-info">
            <div class="profile-photo">
            <p>photo</p>
            </div>

            <div class="user-details">
                <h3>User Name</h3>
                <p>Number of post: x</p>
            </div>
        </div>

        <div class="bio">
        <h3>Bio</h3>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate. Sed vel dolor porttitor felis aliquam tincidunt. Sed nibh orci, dictum sit amet sodales ac, pharetra in augue. Donec rhoncus vehicula magna. Sed laoreet fermentum tincidunt. Curabitur semper elit ac dui commodo, sed lobortis urna varius. Nulla risus neque, euismod ut ante ut, scelerisque luctus leo. Fusce congue dui at eros porta lacinia.
        </div>

        <ul class="post-list">
          <li>
            <h3>Post #1</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate.
            </p>
            <p class='likes-coomments'>Comments: x, Likes:x</p>
          </li>
          <li>
            <h3>Post #2</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate.
            </p>
            <p class='likes-coomments'>Comments: x, Likes:x</p>
          </li>
          <li>
            <h3>Post #3</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer semper lacus eu nibh hendrerit, a rhoncus magna vulputate.
            </p>
            <p class='likes-coomments'>Comments: x, Likes:x</p>
          </li>
        </ul>
        <button class="all-posts">See all posts</button>
    </div>
  </body>
</html>